name: Test library on pull request into develop

on:
  pull_request

jobs:
  test:
    name: Test library
    runs-on: ubuntu-latest
    timeout-minutes: 10
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
    
    - name: say hello
      run: echo "Hello, world!"
    
    - name: error
      run: python3 sample.py